### ISSUE TITLE
Script error(make the sounds dont work)

### ISSUE THREAD

**Issue by Sophia-eros** [Tanookimatt/char-select-Ojamajo-Pack#1]
i playing the mod, and every time a use the characters one error apear and the sounds of the characters dont work. i dont know how make a script so, i dont know what is making this error. If you can help me i would appreciat it

**Comment by Sophia-eros** [comment]
ok i dumb, its the version of my character select. Im sorry for make you read that, i am very sorry.

**Comment by Tanookimatt** [comment]
It’s no problem, sorry I missed this! Glad you got it figured out!
